name: Deploy to Main Server

on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Main Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.MAIN_SSH_USER }}
          key: ${{ secrets.MAIN_SSH_PRIVATE_KEY }}
          script: |
            cd /home/whistleworks-admin/htdocs/https://admin.whistleworks.org/
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
